# Robot model information
robot_info:
  model: "RB3-730ES-U"
  reach: 0.730 # meters
  payload: 3.0 # kg
  dof: 6

# Joint limits in degrees (will be converted to radians internally)
joint_limits:
  # Joint limits based on RB3-730 specifications
  j1: #base
    min: -360 # degrees
    max: 360 # degrees
  # j2:
  #   min: -360  # degrees
  #   max: 360   # degrees
  j2: # shoulder
    min: -360 # degrees
    max: 360 # degrees for table-mounted arm (-90째 to +180째 or -120째 to +150째)
  j3: # elbow
    min: -150 # degrees (RB3-730 specific limit)
    max: 150 # degrees
  j4: # wrist 1
    min: -360 # degrees
    max: 360 # degrees
  j5: # wrist 2
    min: -360 # degrees
    max: 360 # degrees
  j6: # wrist 3
    min: -360 # degrees
    max: 360 # degrees

# Workspace boundaries in meters
# Robot base mounted on floor (z=0), working above 60mm wood surface
workspace:
  x_min: -0.7 # meters (within robot reach)
  x_max: 0.7 # meters
  y_min: -0.7 # meters
  y_max: 0.7 # meters
  z_min: 0.06 # 60mm above floor (wood surface level)
  z_max: 1.1 # meters (maximum reach height)

# Environmental constraints (handled directly in code)
# 1. Floor constraint: Robot base mounted at z=0
# 2. Wood surface constraint: 60mm thick working surface 
# 3. Workspace limits: Defined in workspace section above
environment:
  floor_level: 0.0        # Robot base mounted at floor (z=0)
  wood_thickness: 0.06    # 60mm thick wood surface
  wood_area: [1.4, 1.0]   # 1.4m x 1.0m working area

# Self-collision parameters (derived from RB3-730ES-U URDF)
self_collision:
  enabled: true
  robot_model: "RB3-730ES-U"
  # Key dimensions from URDF (meters)
  base_height: 0.1453      # Base joint height
  upper_arm_length: 0.286  # Shoulder to elbow  
  forearm_length: 0.344    # Elbow to wrist2
  tcp_extension: 0.1       # Wrist3 to TCP
  # Critical joint pairs with minimum safe distances (meters)
  critical_pairs:
    shoulder_wrist2: 0.12    # Upper arm vs wrist assembly
    shoulder_wrist3: 0.10    # Upper arm vs wrist3
    shoulder_tcp: 0.15       # Upper arm vs end effector
    elbow_base: 0.18         # Forearm vs base (145mm base + margin)
    wrist1_base: 0.16        # Wrist1 vs base
    wrist2_base: 0.16        # Wrist2 vs base

orientation_limits:
  enabled: false
  roll_min: -180
  roll_max: 180
  pitch_min: -90
  pitch_max: 90
  yaw_min: -180
  yaw_max: 180

# Safety margins (reduces effective workspace for extra safety)
safety_margins:
  enabled: true
  margin_x: 0.05 # meters - reduce X workspace by this amount on each side
  margin_y: 0.05 # meters - reduce Y workspace by this amount on each side
  margin_z: 0.05 # meters - reduce Z workspace by this amount on top/bottom

# Workspace validation settings
validation:
  path_resolution: 0.01 # meters - check every 1cm along path
  strict_boundaries: true # reject ANY point outside boundaries
  shape: "rectangular" # currently only rectangular supported

# Planning configuration
planning:
  default_num_waypoints: 10
  trajectory_smoothing:
    enabled: true
    iterations: 2
  quality_metrics:
    smoothness_threshold: 0.1 # rad/waypoint
    max_velocity_threshold: 1.0 # rad/s
    max_jerk_threshold: 10.0 # rad/s^3

# Description and notes
description: |
  Consolidated robot configuration file for RB3-730ES-U robot.

  All spatial dimensions are in meters (SI units) for consistency.
  All angular dimensions are in degrees and converted to radians internally.

  Coordinate system:
  - X: Forward(+) / Backward(-) from robot base
  - Y: Right(+) / Left(-) from robot base  
  - Z: Up(+) / Down(-) from robot base

  Safety margins create a smaller "safe zone" within the physical boundaries
  to account for robot dynamics, sensor noise, and mechanical tolerances.
