# Robot model information
robot_info:
  model: "RB3-730ES-U"
  reach: 0.730 # meters
  payload: 3.0 # kg
  dof: 6

# Joint limits in degrees (will be converted to radians internally)
joint_limits:
  # Joint limits based on RB3-730 specifications
  j1: #base
    min: -360 # degrees
    max: 360 # degrees
  # j2:
  #   min: -360  # degrees
  #   max: 360   # degrees
  j2: # shoulder
    min: -360 # degrees
    max: 360 # degrees for table-mounted arm (-90째 to +180째 or -120째 to +150째)
  j3: # elbow
    min: -150 # degrees (RB3-730 specific limit)
    max: 150 # degrees
  j4: # wrist 1
    min: -360 # degrees
    max: 360 # degrees
  j5: # wrist 2 (limited when tool/gripper attached)
    min: -180 # degrees (realistic limit with tool attached)
    max: 180 # degrees (prevents cable wrap/tool collision)
  j6: # wrist 3 (tool rotation - limited by cables/pneumatics)
    min: -270 # degrees (realistic limit with tool cables)
    max: 270 # degrees (prevents excessive cable twist)

# Workspace boundaries in meters
# Robot base mounted on floor (z=0), working above 60mm wood surface
# UPDATED: Extended workspace to utilize robot's full 730mm reach capability
# Based on URDF analysis and real robot data showing 877mm vertical reach
workspace:
  x_min: -0.75 # meters (extended from -0.72 to support 700mm+ reach)
  x_max: 0.75 # meters (extended from 0.72 to support 700mm+ reach)
  y_min: -0.75 # meters (extended from -0.72 to support 700mm+ reach)
  y_max: 0.75 # meters (extended from 0.72 to support 700mm+ reach)
  z_min: 0.06 # 60mm above floor (wood surface level)
  z_max: 1.1 # meters (maximum reach height)

# Environmental constraints (handled directly in code)
# 1. Floor constraint: Robot base mounted at z=0
# 2. Wood surface constraint: 60mm thick working surface 
# 3. Workspace limits: Defined in workspace section above
environment:
  floor_level: 0.0        # Robot base mounted at floor (z=0)
  wood_thickness: 0.05    # 50mm thick wood surface
  wood_area: [1.4, 1.0]   # 1.4m x 1.0m working area

# Self-collision parameters (UPDATED for RB3-730ES-U based on real robot dimensions)
# Further optimized to increase practical reach to ~650mm
self_collision:
  enabled: true
  robot_model: "RB3-730ES-U"
  # Key dimensions from MANUFACTURER SPECIFICATIONS (meters)
  base_height: 0.1453      # Base joint height (B = 145.3mm - CONFIRMED)
  upper_arm_length: 0.286  # Shoulder to elbow (C = 286mm - CONFIRMED) 
  forearm_length: 0.344    # Elbow to wrist2 (D = 344mm - CONFIRMED)
  tcp_extension: 0.1       # Wrist3 to TCP (E = 100mm - CONFIRMED)
  # Additional manufacturer dimensions for precise collision calculation
  total_height: 0.730      # A = 730mm (full reach)
  dimension_f: 0.11715     # F = 117.15mm
  dimension_g: 0.1107      # G = 110.7mm  
  dimension_h: 0.0946      # H = 94.6mm
  # Critical joint pairs with MODERATE distances for 680mm reach
  # Balanced between safety and extended reach capability
  critical_pairs:
    shoulder_wrist2: 0.030   # J1-J4: MODERATE - 30mm (was 25mm aggressive)
    shoulder_wrist3: 0.030   # J1-J5: MODERATE - 30mm (was 25mm aggressive)  
    shoulder_tcp: 0.035      # J1-J6: MODERATE - 35mm (was 30mm aggressive)
    elbow_base: 0.035        # J2-J0: MODERATE - 35mm (was 30mm aggressive)
    wrist1_base: 0.035       # J3-J0: MODERATE - 35mm (was 30mm aggressive)
    wrist2_base: 0.035       # J4-J0: MODERATE - 35mm (was 30mm aggressive)
  # Extended reach parameters - MODERATE for 650-680mm target reach
  extended_reach_parameters:
    enabled: true
    max_reach: 0.680          # MODERATE: Realistic target reach (680mm)
    safety_coefficient: 0.90  # MODERATE: Balanced safety vs reach

# Safety margins (reduces effective workspace for extra safety)
# Further reduced margins to allow extended reach capabilities
safety_margins:
  enabled: true
  margin_x: 0.01 # meters - reduced from 0.02 to 0.01 (10mm vs 20mm)
  margin_y: 0.01 # meters - reduced margin for better workspace utilization
  margin_z: 0.008 # meters - reduced from 0.015 to 0.008 to allow 68mm minimum (60+8=68mm)

# Enhanced collision detection settings
# AGGRESSIVE: Optimized for maximum 700mm reach with distance-adaptive thresholds
collision_detection:
  adaptive_thresholds: true          # Enable adaptive collision thresholds
  operational_safety_factor: 0.98    # AGGRESSIVE: Reduced for maximum reach (was 1.01)
  edge_case_tolerance: 3.0           # INCREASED: Maximum tolerance for extended reach (was 2.5)
  escape_perturbation_enabled: true  # Allow escape perturbations when stuck
  minimum_threshold_mm: 8.0          # REDUCED: Absolute minimum threshold (was 10.0mm)
  home_position_exception: true      # Special handling for home position
  single_joint_movement_factor: 0.75 # REDUCED: Very relaxed for single movements (was 0.80)
  wrist_joint_special_case: true     # Special handling for wrist joints (J3-J5)
  allow_standard_poses: true         # Allow common robot poses without collision flagging
  extended_reach_mode: true          # ENABLED: Special handling for positions at 650-700mm reach
  # NEW: Distance-adaptive collision scaling
  distance_adaptive_scaling:
    enabled: true
    # Scale collision thresholds based on TCP distance from base
    scaling_zones:
      - distance_max: 500           # Up to 500mm: normal collision detection
        scale_factor: 1.0
      - distance_max: 600           # 500-600mm: slightly relaxed
        scale_factor: 0.9
      - distance_max: 680           # 600-680mm: more relaxed
        scale_factor: 0.8
      - distance_max: 750           # 680-750mm: maximum relaxation
        scale_factor: 0.7

# Workspace validation settings
validation:
  path_resolution: 0.01 # meters - check every 1cm along path
  strict_boundaries: true # reject ANY point outside boundaries
  shape: "rectangular" # currently only rectangular supported
  adaptive_validation: true # Enable adaptive validation based on pose complexity

# Planning configuration
planning:
  default_num_waypoints: 10
  trajectory_smoothing:
    enabled: true
    iterations: 2
  quality_metrics:
    smoothness_threshold: 0.1 # rad/waypoint
    max_velocity_threshold: 1.0 # rad/s
    max_jerk_threshold: 10.0 # rad/s^3

# Tool/Gripper Configuration
tools:
  # Default gripper configuration (2-finger parallel gripper)
  default_gripper:
    name: "Parallel 2-Finger Gripper"
    type: "parallel_gripper"
    enabled: true
    
    # Tool transformation from TCP to gripper functional point
    # TCP to gripper center point transformation
    tcp_to_tool_offset:
      # Translation from TCP to gripper center (meters)
      translation: [0.0, 0.0, 0.085]  # 85mm extension in Z (TCP forward)
      # Rotation from TCP frame to gripper frame (RPY in degrees)
      rotation: [0.0, 0.0, 0.0]       # No rotation (gripper aligned with TCP)
    
    # Gripper geometry (for collision checking and workspace analysis)
    geometry:
      # Gripper body dimensions (length x width x height in meters)
      body_size: [0.06, 0.04, 0.02]   # 60x40x20mm gripper body
      # Finger dimensions when closed
      finger_length: 0.03             # 30mm finger length
      finger_width: 0.008             # 8mm finger width
      finger_thickness: 0.005         # 5mm finger thickness
      # Maximum gripper opening
      max_opening: 0.05               # 50mm max opening
      
    # Gripper operation parameters
    operation:
      # Force and speed limits
      max_force: 40.0                 # Maximum gripping force (N)
      max_speed: 0.1                  # Maximum closing speed (m/s)
      # Grasp detection
      force_threshold: 5.0            # Force threshold for grasp detection (N)
      position_tolerance: 0.001       # Position tolerance for grasp (m)
      
    # Workspace modifications when gripper is attached
    workspace_impact:
      # Additional safety margins due to gripper geometry
      margin_increase: [0.03, 0.02, 0.02]  # Increase X,Y,Z margins by 30,20,20mm
      # Restricted zones (relative to TCP frame)
      restricted_orientations:
        # Avoid extreme wrist orientations that could cause gripper collisions
        min_wrist_2_angle: -150        # degrees (J5)
        max_wrist_2_angle: 150         # degrees (J5)

  # Template for custom grippers
  custom_gripper_template:
    name: "Custom Gripper Template"
    type: "custom"
    enabled: false
    tcp_to_tool_offset:
      translation: [0.0, 0.0, 0.0]    # Define your tool offset
      rotation: [0.0, 0.0, 0.0]       # Define orientation offset
    geometry:
      # Define your gripper geometry
      body_size: [0.0, 0.0, 0.0]
      # Add any custom geometry parameters
    # Add any custom parameters for your specific gripper

# Tool selection (which tool is currently attached)
active_tool:
  current: "default_gripper"          # Name of currently attached tool
  auto_detect: false                  # Whether to auto-detect tool presence

# Description and notes
description: |
  Consolidated robot configuration file for RB3-730ES-U robot.

  All spatial dimensions are in meters (SI units) for consistency.
  All angular dimensions are in degrees and converted to radians internally.

  IMPORTANT: Joint limits are configured for production use with tools/grippers attached.
  J5 and J6 limits are conservative to account for:
  - Tool/gripper geometry and collision avoidance
  - Cable management (power, pneumatic, communication cables)
  - Mechanical stress on wrist joints when carrying payload
  - Practical accessibility for maintenance and operation

  Coordinate system:
  - X: Forward(+) / Backward(-) from robot base
  - Y: Right(+) / Left(-) from robot base  
  - Z: Up(+) / Down(-) from robot base

  Safety margins create a smaller "safe zone" within the physical boundaries
  to account for robot dynamics, sensor noise, and mechanical tolerances.

  TOOL COORDINATE SYSTEMS:
  - TCP (Tool Center Point): The robot's native end-effector reference point
  - Tool Functional Point: The actual working point of the attached tool
  - For grippers: Usually the center point between fingers when closed
  - Tool offset transforms TCP coordinates to functional coordinates
