# Robot model information
robot_info:
  model: "RB3-730ES-U"
  reach: 0.730 # meters
  payload: 3.0 # kg
  dof: 6

# Joint limits in degrees (will be converted to radians internally)
joint_limits:
  # Joint limits based on RB3-730 specifications
  j1: #base
    min: -360 # degrees
    max: 360 # degrees
  # j2:
  #   min: -360  # degrees
  #   max: 360   # degrees
  j2: # shoulder
    min: -360 # degrees
    max: 360 # degrees for table-mounted arm (-90째 to +180째 or -120째 to +150째)
  j3: # elbow
    min: -150 # degrees (RB3-730 specific limit)
    max: 150 # degrees
  j4: # wrist 1
    min: -360 # degrees
    max: 360 # degrees
  j5: # wrist 2 (limited when tool/gripper attached)
    min: -180 # degrees (realistic limit with tool attached)
    max: 180 # degrees (prevents cable wrap/tool collision)
  j6: # wrist 3 (tool rotation - limited by cables/pneumatics)
    min: -270 # degrees (realistic limit with tool cables)
    max: 270 # degrees (prevents excessive cable twist)

# Workspace boundaries in meters
# Robot base mounted on floor (z=0), working above 60mm wood surface
# Updated to reflect actual robot reach (730mm theoretical, ~720mm practical)
workspace:
  x_min: -0.72 # meters (conservative limit based on 730mm reach)
  x_max: 0.72 # meters
  y_min: -0.72 # meters
  y_max: 0.72 # meters
  z_min: 0.06 # 60mm above floor (wood surface level)
  z_max: 1.1 # meters (maximum reach height)

# Environmental constraints (handled directly in code)
# 1. Floor constraint: Robot base mounted at z=0
# 2. Wood surface constraint: 60mm thick working surface 
# 3. Workspace limits: Defined in workspace section above
environment:
  floor_level: 0.0        # Robot base mounted at floor (z=0)
  wood_thickness: 0.06    # 60mm thick wood surface
  wood_area: [1.4, 1.0]   # 1.4m x 1.0m working area

# Self-collision parameters (MANUFACTURER VALIDATED - RB3-730ES-U Official Specs)
self_collision:
  enabled: true
  robot_model: "RB3-730ES-U"
  # Key dimensions from OFFICIAL MANUFACTURER SPECIFICATIONS (meters)
  base_height: 0.1453      # Base joint height (B = 145.3mm - CONFIRMED)
  upper_arm_length: 0.286  # Shoulder to elbow (C = 286mm - CONFIRMED) 
  forearm_length: 0.344    # Elbow to wrist2 (D = 344mm - CONFIRMED)
  tcp_extension: 0.1       # Wrist3 to TCP (E = 100mm - CONFIRMED)
  # Additional manufacturer dimensions for precise collision calculation
  total_height: 0.730      # A = 730mm (full reach)
  dimension_f: 0.11715     # F = 117.15mm
  dimension_g: 0.1107      # G = 110.7mm  
  dimension_h: 0.0946      # H = 94.6mm
  # Critical joint pairs with MANUFACTURER-BASED minimum safe distances (meters)
  # Calculated from official dimensional drawings and link geometry
  critical_pairs:
    shoulder_wrist2: 0.045   # Upper arm vs wrist assembly (45mm - based on link thickness)
    shoulder_wrist3: 0.025   # Upper arm vs wrist3 (25mm - allows tight folding configs)
    shoulder_tcp: 0.055      # Upper arm vs end effector (55mm - includes TCP extension)
    elbow_base: 0.090        # Forearm vs base (90mm - realistic for 145.3mm base)
    wrist1_base: 0.075       # Wrist1 vs base (75mm - wrist housing clearance)
    wrist2_base: 0.075       # Wrist2 vs base (75mm - wrist housing clearance)

# Safety margins (reduces effective workspace for extra safety)
# Reduced margins to allow more of the robot's actual workspace
safety_margins:
  enabled: true
  margin_x: 0.02 # meters - reduced from 0.05 to 0.02 (20mm vs 50mm)
  margin_y: 0.02 # meters - reduced margin for better workspace utilization
  margin_z: 0.03 # meters - slightly reduced Z margin

# Enhanced collision detection settings
# Relaxed settings to better utilize robot workspace while maintaining safety
collision_detection:
  adaptive_thresholds: true          # Enable adaptive collision thresholds
  operational_safety_factor: 1.0     # Reduced from 0.95 to 1.0 (less restrictive)
  edge_case_tolerance: 1.3           # Increased tolerance for complex configurations
  escape_perturbation_enabled: true  # Allow escape perturbations when stuck

# Workspace validation settings
validation:
  path_resolution: 0.01 # meters - check every 1cm along path
  strict_boundaries: true # reject ANY point outside boundaries
  shape: "rectangular" # currently only rectangular supported
  adaptive_validation: true # Enable adaptive validation based on pose complexity

# Planning configuration
planning:
  default_num_waypoints: 10
  trajectory_smoothing:
    enabled: true
    iterations: 2
  quality_metrics:
    smoothness_threshold: 0.1 # rad/waypoint
    max_velocity_threshold: 1.0 # rad/s
    max_jerk_threshold: 10.0 # rad/s^3

# Tool/Gripper Configuration
tools:
  # Default gripper configuration (2-finger parallel gripper)
  default_gripper:
    name: "Parallel 2-Finger Gripper"
    type: "parallel_gripper"
    enabled: true
    
    # Tool transformation from TCP to gripper functional point
    # TCP to gripper center point transformation
    tcp_to_tool_offset:
      # Translation from TCP to gripper center (meters)
      translation: [0.0, 0.0, 0.085]  # 85mm extension in Z (TCP forward)
      # Rotation from TCP frame to gripper frame (RPY in degrees)
      rotation: [0.0, 0.0, 0.0]       # No rotation (gripper aligned with TCP)
    
    # Gripper geometry (for collision checking and workspace analysis)
    geometry:
      # Gripper body dimensions (length x width x height in meters)
      body_size: [0.06, 0.04, 0.02]   # 60x40x20mm gripper body
      # Finger dimensions when closed
      finger_length: 0.03             # 30mm finger length
      finger_width: 0.008             # 8mm finger width
      finger_thickness: 0.005         # 5mm finger thickness
      # Maximum gripper opening
      max_opening: 0.05               # 50mm max opening
      
    # Gripper operation parameters
    operation:
      # Force and speed limits
      max_force: 40.0                 # Maximum gripping force (N)
      max_speed: 0.1                  # Maximum closing speed (m/s)
      # Grasp detection
      force_threshold: 5.0            # Force threshold for grasp detection (N)
      position_tolerance: 0.001       # Position tolerance for grasp (m)
      
    # Workspace modifications when gripper is attached
    workspace_impact:
      # Additional safety margins due to gripper geometry
      margin_increase: [0.03, 0.02, 0.02]  # Increase X,Y,Z margins by 30,20,20mm
      # Restricted zones (relative to TCP frame)
      restricted_orientations:
        # Avoid extreme wrist orientations that could cause gripper collisions
        min_wrist_2_angle: -150        # degrees (J5)
        max_wrist_2_angle: 150         # degrees (J5)

  # Template for custom grippers
  custom_gripper_template:
    name: "Custom Gripper Template"
    type: "custom"
    enabled: false
    tcp_to_tool_offset:
      translation: [0.0, 0.0, 0.0]    # Define your tool offset
      rotation: [0.0, 0.0, 0.0]       # Define orientation offset
    geometry:
      # Define your gripper geometry
      body_size: [0.0, 0.0, 0.0]
      # Add any custom geometry parameters
    # Add any custom parameters for your specific gripper

# Tool selection (which tool is currently attached)
active_tool:
  current: "default_gripper"          # Name of currently attached tool
  auto_detect: false                  # Whether to auto-detect tool presence

# Description and notes
description: |
  Consolidated robot configuration file for RB3-730ES-U robot.

  All spatial dimensions are in meters (SI units) for consistency.
  All angular dimensions are in degrees and converted to radians internally.

  IMPORTANT: Joint limits are configured for production use with tools/grippers attached.
  J5 and J6 limits are conservative to account for:
  - Tool/gripper geometry and collision avoidance
  - Cable management (power, pneumatic, communication cables)
  - Mechanical stress on wrist joints when carrying payload
  - Practical accessibility for maintenance and operation

  Coordinate system:
  - X: Forward(+) / Backward(-) from robot base
  - Y: Right(+) / Left(-) from robot base  
  - Z: Up(+) / Down(-) from robot base

  Safety margins create a smaller "safe zone" within the physical boundaries
  to account for robot dynamics, sensor noise, and mechanical tolerances.

  TOOL COORDINATE SYSTEMS:
  - TCP (Tool Center Point): The robot's native end-effector reference point
  - Tool Functional Point: The actual working point of the attached tool
  - For grippers: Usually the center point between fingers when closed
  - Tool offset transforms TCP coordinates to functional coordinates
